version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=true
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_WORKSPACE_SSH=false
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
           - "22:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
                - INSTALL_AEROSPIKE_EXTENSION=true
            dockerfile: Dockerfile-56
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"

### Apache Server Container ##################################

    apache2:
        build:
            context: ./apache2
            args:
                - PHP_SOCKET="php-fpm:9000"
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/apache2:/var/log/apache2
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: unibanco
            MYSQL_USER: uni
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: root

### phpMyAdmin Container ##################################

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: uni
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: root
        volumes_from:
            - volumes_data
        ports:
            - "8080:80"
        links:
            # for mysql container
            - "mysql:db"
            # for mariadb container
            # - "mariadb:db"

### Laravel Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www/laravel
            # Demonstration of how to mount multiple sites
            # - ../../site_a/:/var/www/site_a
            # - ../../site_b/:/var/www/site_b

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/postgres:/var/lib/postgresql/data
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/neo4j:/var/lib/neo4j/data
            - ./data/mongo:/data/db
            - ./data/aerospike:/opt/aerospike/data
            - ./data/sessions:/sessions
            - ./data/caddy:/root/.caddy
            - ./data/elasticsearch/data:/usr/share/elasticsearch/data

### Add more Containers below ###############################
